### ISSUE TITLE
Chinese Support Not So Friendly

### ISSUE THREAD

**Issue by willin** [jonschlinkert/marked-toc#1]
Example:

``` markdown
# MQTT 相关
## 返回 MQTT 服务器信息接口
```

To HTML is:

``` html
<h1 id="mqtt-%E7%9B%B8%E5%85%B3">MQTT 相关</h1>
<h2 id="%E8%BF%94%E5%9B%9E-mqtt-%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%BF%A1%E6%81%AF%E6%8E%A5%E5%8F%A3">返回 MQTT 服务器信息接口</h2>
```

but the TOC Link is:

``` html
<a href="#mqtt-相关">MQTT 相关</a>
<a href="#返回-mqtt-服务器信息接口">返回 MQTT 服务器信息接口</a>
```

to resolve this problem you need to `url_encode` before output

**Comment by jonschlinkert** [comment]
This [repository was deprecated](https://github.com/jonschlinkert/marked-toc#deprecated). Please use [markdown-toc](https://github.com/jonschlinkert/markdown-toc) instead
